"model":
  "type": "remake"
  "params":
    "lambda_val": 1
    "res": True

"optimizer":
  "type": "AdamW"
  "params":
    "lr": 0.001 #

"lr_scheduler":
  "type": "MultiStepLR"
  "params":
    "milestones": [35, 65] #
    "gamma": 0.1

"dataset":
  "train":
    "type": "cleargrasp-syn"
    "data_dir": "datasets/cleargrasp"
    "image_size": !!python/tuple [640, 480]
    "use_augmentation": True
    "rgb_augmentation_probability": 0.8
    "use_depth_augmentation": False
    "no_mask_depth": False
    "depth_min": 0.3
    "depth_max": 1.5
    "depth_norm": 1.0
    "reldepth_model": depthanything
  "test":
    "type": "cleargrasp-real"
    "data_dir": "datasets/cleargrasp"
    "image_size": !!python/tuple [640, 480] #[320, 240]
    "use_augmentation": False
    "depth_min": 0.3
    "depth_max": 1.5
    "depth_norm": 1.0
    "reldepth_model": depthanything

"dataloader":
  "num_workers": 8 
  "shuffle": True # True multigpu should be false
  "drop_last": False #

"trainer":
  "batch_size": 6 
  "test_batch_size": 18
  "multigpu": True # False
  "max_epoch": 40   #120
  "criterion":
    "type": "l1_loss"
    "epsilon": 0.00000001
    "combined_smooth": True
    "combined_beta": 0.1

"metrics":
  "types": ["MSE", "RMSE", "REL", "MAE", "Threshold@1.01", "Threshold@1.03", "Threshold@1.05", "Threshold@1.10", "Threshold@1.25", "MaskedMSE", "MaskedRMSE", "MaskedREL", "MaskedMAE", "MaskedThreshold@1.01", "MaskedThreshold@1.03", "MaskedThreshold@1.05", "MaskedThreshold@1.10", "MaskedThreshold@1.25", "ssim"]
  "epsilon": 0.00000001
  "depth_scale": 1.0

"states":
  "states_dir": "results"
  "states_exper": "train-cgsyn-val-cgsyn-dfuse"

"tb_log":
  "states_dir": "tb_log"
  "states_exper": "train-cgsyn-val-cgsyn"