# script id: 1
"model":
  "type": "dfnet"
  "params":
    "in_channels": 4
    "hidden_channels": 64
    "layer_num": 5
    "k": 12

"optimizer":
  "type": "AdamW"
  "params":
    "lr": 0.001

"lr_scheduler":
  "type": "MultiStepLR"
  "params":
    "milestones": [5, 15, 25, 35]
    "gamma": 0.2

"dataset":
  "train":
    - "type": "cleargrasp-syn"
      "data_dir": "datasets/cleargrasp"
      "image_size": !!python/tuple [320, 240]
      "depth_min": 0.3
      "depth_max": 1.5
      "depth_norm": 1.0
  "test":
    - "type": "cleargrasp-real"
      "data_dir": "datasets/cleargrasp"
      "image_size": !!python/tuple [320, 240]
      "depth_min": 0.3
      "depth_max": 1.5
      "depth_norm": 1.0

  "train":
    "type": "cleargrasp-syn"
    "data_dir": "datasets/cleargrasp"
    "image_size": !!python/tuple [320, 240]
    "use_augmentation": True
    "rgb_augmentation_probability": 0.8
    "use_depth_augmentation": False
    "depth_min": 0.0
    "depth_max": 10.0
  "test":
    "type": "cleargrasp-real"
    "data_dir": "datasets/cleargrasp"
    "image_size": !!python/tuple [320, 240]
    "use_augmentation": False
    "depth_min": 0.0
    "depth_max": 10.0
    "depth_norm": 1.0

"dataloader":
  "num_workers": 8
  "shuffle": True
  "drop_last": True

"trainer":
  "batch_size": 32
  "test_batch_size": 1
  "multigpu": False
  "max_epoch": 40  
  "criterion":
    "type": "custom_masked_mse_loss"
    "epsilon": 0.00000001

"metrics":
  "types": ["MaskedMSE", "MaskedRMSE", "MaskedREL", "MaskedMAE", "MaskedThreshold@1.01", "MaskedThreshold@1.03", "MaskedThreshold@1.01", "MaskedThreshold@1.03", "MaskedThreshold@1.05", "MaskedThreshold@1.15", "MaskedThreshold@1.25"]
  "epsilon": 0.00000001
  "depth_scale": 1.0

"states":
  "states_dir": "results"
  "states_exper": "train-tg-val-tg-dfnet"

